# Generated by Django 5.1.5 on 2025-02-17 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_property_key_features_alter_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='key_features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
