# Generated by Django 5.1.5 on 2025-02-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_remove_property_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('sold_out', 'Sold Out'), ('for_rent', 'For Rent'), ('under_offer', 'Under Offer')], default='for_sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
