# Generated by Django 5.1.5 on 2025-02-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_remove_property_updated_at_property_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('under_offer', 'Under Offer')], default='for_sale', max_length=20),
        ),
    ]
