# Generated by Django 5.1.5 on 2025-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0022_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('under_offer', 'Under Offer')], default='Available', max_length=20),
        ),
    ]
