# Generated by Django 5.1.5 on 2025-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0023_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('under_offer', 'Under Offer')], default='for_sale', max_length=20),
        ),
    ]
