# Generated by Django 5.1.5 on 2025-03-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_property_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending')], default='available', max_length=20),
        ),
    ]
