# Generated by Django 5.1.5 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0030_remove_order_created_at_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
